### ISSUE TITLE
Sequences are disabled for Redshift

### ISSUE THREAD

**Issue by jobevers** [binarydud/redshift_sqlalchemy#24] opened 2014-12-25 01:15 UTC
When making an integer primary key, sqlalchemy wants to also create a sequence, which are unsupported: http://docs.aws.amazon.com/redshift/latest/dg/c_unsupported-postgresql-features.html.

**Comment by GabKlein** [comment] 2015-03-07 01:42
+1

**Comment by graingert** [comment] 2015-05-11 11:23
This is a duplicate of #9 and fixed in https://pypi.python.org/pypi/sqlalchemy-redshift/0.1.0

**Comment by nwbvt** [comment] 2015-09-03 18:57
I'm still seeing this on version 0.4

**Closed** 2015-09-26 01:58 UTC
